name: Node.js CI/CD to ECS

on:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: nodejs-app-design
  ECS_CLUSTER: ubioworo-cluster
  ECS_SERVICE: my-node-service
  CONTAINER_NAME: nodejs-app
  IMAGE_TAG: latest

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: space-shooter-node/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('space-shooter-node/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./space-shooter-node

      - name: Run tests
        run: npx jest --coverage --detectOpenHandles
        working-directory: ./space-shooter-node

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create ECS Cluster if not exists
        run: |
          aws ecs describe-clusters --clusters ${{ env.ECS_CLUSTER }} --region ${{ secrets.AWS_REGION }} \
            || aws ecs create-cluster --cluster-name ${{ env.ECS_CLUSTER }} --region ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t ${{ env.CONTAINER_NAME }}:$IMAGE_TAG ./space-shooter-node

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.CONTAINER_NAME }}:$IMAGE_TAG
          format: table
          exit-code: 1       # Fail if vulnerabilities found
          ignore-unfixed: true

      - name: Tag and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker tag ${{ env.CONTAINER_NAME }}:$IMAGE_TAG $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
